auth:
  enabled: true
  password: ebus@Valkey2026

primary:
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

replica:
  replicaCount: 1
  persistence:
    enabled: true
    size: 2Gi
