apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgbouncer-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"    # deploy after patroni (wave 1)
spec:
  project: prod

  source:
    repoURL: https://github.com/sachinkhosla-DevOps/pm-ebus-infra
    targetRevision: main
    path: environments/prod/pgbouncer

  destination:
    server: https://YOUR-EKS-API-ENDPOINT.gr7.ap-south-1.eks.amazonaws.com
    namespace: patroni

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
