apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"    # operator first
spec:
  project: default
  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 1.0.1
    helm:
      values: |
        watchNamespaces:
          - kafka
        resources:
          requests:
            cpu: 200m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 512Mi
        logLevel: INFO
        createGlobalResources: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
