apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patroni-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sachinkhosla-DevOps/pm-ebus-infra
    targetRevision: main
    path: environments/dev/patroni

  destination:
    server: https://kubernetes.default.svc    # local Minikube
    namespace: patroni

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
