apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patroni
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/sachinkhosla-DevOps/pm-ebus-infra
    targetRevision: main
    path: patroni
  destination:
    server: https://kubernetes.default.svc
    namespace: patroni
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
